FROM holoscan-sdk-dev

ARG DEBIAN_FRONTEND=noninteractive

#
# Holoscan SDK
#

COPY ./holoscan-sdk /workspace/holoscan-sdk

RUN cd /workspace/holoscan-sdk && \
    rm -fr build && \
    mkdir build && \
    cd build && \
    cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release \
                      -DEXPECTED_ENABLE_TESTS=OFF \
                      -DHOLOSCAN_BUILD_EXAMPLES=ON \
                      -DHOLOSCAN_BUILD_TESTS=OFF \
                      -DHOLOSCAN_BUILD_LIBTORCH=OFF && \
    ninja install

#
# Advanced Network Operator
#

COPY ./holohub /workspace/holohub

# Install MLX5 (Advanced Network Dependency) [**ARCH DEPENDENT**]

RUN wget -q https://content.mellanox.com/ofed/MLNX_OFED-5.8-1.0.1.1/MLNX_OFED_LINUX-5.8-1.0.1.1-ubuntu20.04-x86_64.tgz && \
    tar xf MLNX_OFED_LINUX-5.8-1.0.1.1-ubuntu20.04-x86_64.tgz && \
    cd MLNX_OFED_LINUX-5.8-1.0.1.1-ubuntu20.04-x86_64 && \
    ./mlnxofedinstall --upstream-libs --dpdk --with-mft --upstream-libs --user-space-only --force --without-fw-update

# Install DPDK (Advanced Network Dependency)

RUN apt update && \
    apt install --no-install-recommends -y \
        build-essential \
        python3-pyelftools \
        libnuma-dev \
        && rm -rf /var/lib/apt/lists/*

RUN apt update && \
    apt install --no-install-recommends -y \
        python3-dev \
        python3-pip \
        && rm -rf /var/lib/apt/lists/*
RUN python3 -m pip install meson ninja

RUN wget -q https://fast.dpdk.org/rel/dpdk-22.11.4.tar.xz && \
    tar xf dpdk-22.11.4.tar.xz && \
    cd dpdk-stable-22.11.4/ && \
    patch --ignore-whitespace --fuzz 3 \
        config/arm/meson.build \
        /workspace/holohub/operators/advanced_network/dpdk_patches/dpdk.nvidia.patch && \
    patch --ignore-whitespace --fuzz 3 \
        drivers/gpu/cuda/devices.h \
        /workspace/holohub/operators/advanced_network/dpdk_patches/devices.h.patch && \
    patch --ignore-whitespace --fuzz 3 \
        drivers/gpu/cuda/cuda.c \
        /workspace/holohub/operators/advanced_network/dpdk_patches/cuda.c.patch && \
    meson build -Dplatform=generic -Dc_args=-I/usr/local/cuda/include && \
    ninja -C build install

# Install Advanced Network Operator

RUN apt update && \
    apt install --no-install-recommends -y \
        pkg-config \
        && rm -rf /var/lib/apt/lists/*

COPY ./patches /workspace/patches
RUN cd /workspace/holohub/operators/advanced_network && \
    patch -p1 < /workspace/patches/adv_networking_install.patch && \
    patch -p1 < /workspace/patches/adv_networking.patch && \
    rm -fr build && \
    mkdir build && \
    cd build && \
    cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release && \
    ninja install