%YAML 1.2
---
multithreaded: true
num_delay_ops: 32
delay: 0.1
delay_step: 0.01

scheduler:
  check_recession_period_ms: 0
  worker_thread_number: 4
  stop_on_deadlock: true
  stop_on_deadlock_timeout: 500

advanced_network:
  cfg:
    version: 1
    master_core: 17                     # Master CPU core
    rx:
      - if_name: 0000:34:00.1           # PCIe BFD of NIC
        flow_isolation: true
        queues:
          - name: "ADC Samples"
            id: 0
            gpu_device: 0
            gpu_direct: true
            split_boundary: 62          # 46 (header) + 16 (rfsoc header)
            cpu_cores: "20"
            max_packet_size: 6210       # Maximum payload size
            num_concurrent_batches: 25  # Number of batches that can be used at any time
            batch_size: 1400            # Number of packets in a batch
            output_port: "bench_rx_out"
        flows:
          - name: "ADC Samples"
            action:
              type: queue
              id: 0
            match:
              udp_src: 10000
              udp_dst: 50000

ata_transport_rx:
  concurrent_blocks: 4
  total_block:
    number_of_antennas: 5
    number_of_channels: 192
    number_of_samples: 8192
    number_of_polarizations: 2
  partial_block:
    number_of_antennas: 1
    number_of_channels: 96
    number_of_samples: 16
    number_of_polarizations: 2
  offset_block:
    number_of_antennas: 0
    number_of_channels: 928
    number_of_samples: 0
    number_of_polarizations: 0
  transport_header_size: 46
  voltage_header_size: 16
  voltage_data_size: 6144

blade_runner:
  blocks:
    - cast
    - channelizer
    - detector
  input:
    type: CU8
    shape: [5, 192, 8192, 2]
  output:
    type: F32
    shape: [5, 1572864, 1, 1]
  config:
    cast:
      module: cast
      input_type: CU8
      output_type: CF32
    channelizer:
      module: channelizer
      input_type: CF32
      output_type: CF32
      rate: 8192
    detector:
      module: detector
      input_type: CF32
      output_type: F32
      integrationSize: 1
      numberOfOutputPolarizations: 1
